### ISSUE TITLE
Proper web framework

### ISSUE THREAD

**Issue by MHOOO** [social-protocols/propolis#15]
I'm not entirely sold on doing things the old-school way. Maybe evaluate some of the [options](https://github.com/flosse/rust-web-framework-comparison) out there?
In particular, I dislike:
* Template parameter structs are located independently of actual template
  * is the HTML actually being verified?
* Templates do not have access to all code, unless explicitly provided via the template parameter struct
* Additional struct for POSTing data is required
* Interactivity suffers: we are kind of back to non-interactive web pages from 1999

Opinions?

*Tasks*

- [ ] Switch away from askama

**Comment by fdietze** [comment]
Regarding interactivity, what could we do to stay lightweight? On the other end of the spectrum is a SPA which I would like to avoid, because that won't be lightweight and simple anymore (probably different programming language, bundling, bigger payload, slower rendering, client-server communication for everything).

But I'd like to explore what's in-between. Maybe there's a good way to do good interactivity and stay lightweight?

**Comment by fdietze** [comment]
Maybe some structs can be avoided by choosing a different templating library? I don't think we can get around structs for client-server communication (POSTing forms).

**Comment by MHOOO** [comment]
> Maybe some structs can be avoided by choosing a different templating library? I don't think we can get around structs for client-server communication (POSTing forms).

I guess when using e.g. https://docs.rs/typed-html/latest/typed_html/ we might get rid of the Template parameter structs, since we could then just use normal rust functions

**Comment by fdietze** [comment]
typed_html looks great, unfortunately it's currently maintained: https://github.com/bodil/typed-html

But if it's stable we could still use it.

**Comment by MHOOO** [comment]
Not sure where that comes from, but yew also appears to have some sort of html macro: https://yew.rs/docs/concepts/html

**Comment by fdietze** [comment]
Here are more template libraries: https://github.com/rosetta-rs/template-benchmarks-rs#rust-template-engine-benchmarks

**Comment by MHOOO** [comment]
Maud looks interesting and simple enough

Felix Dietze ***@***.***> schrieb am Sa., 25. Feb. 2023,
22:47:

**Comment by MHOOO** [comment]
I've used maud partially for the options page in https://github.com/social-protocols/propolis/pull/29
The errors & syntax of the used macro are not always obvious... but neither are the errors & syntax from askama, so I'm fine with that.
In general, I'm pleased with no longer having to write input structs, however, since these are now simple parameters to the respective function. I'm open for comments, though.

**Comment by fdietze** [comment]
Maud looks good! Let's go with that instead of Askama :+1:
