### ISSUE TITLE
Answer: It depends

### ISSUE THREAD

**Issue by fdietze** [social-protocols/propolis#9]
When a question is too generic to answer or when a statement can be interpreted in different ways, the answer is often: "It depends"

Clicking on "it depends":
- save vote in db
- show the create statement screen. But with targeting set to the original statement (see #11 )
- the user can add 1 or more statements
- the new statements will be connected to the original as "specialization"
- it will be put in the queue for users who voted on the original statement (targeting)
- save it in a targeting table?

**Comment by MHOOO** [comment]
If I understand this correctly, with the following statement:
> We need to enforce our immigration laws and secure our borders to protect our country.

*Answer with*: it depends
*Add new statement*: The demographic change requires constant immigration to support pensions.

Now, while I think the second statement can stand on its own, the question would be if we'd want to show this as a sort of *statement thread* or something similar. This way the context, which is about stricter immigration laws, does not get lost.
